package com.germistry.gui;

public enum PanelName {

	MAIN_MENU,
	TWENTY28_MENU,
	TWENTY28_PLAY,
	TWENTY28_LEADERBOARD,
	MINESWEEPER_MENU,
	MINESWEEPER_PLAY,
	MINESWEEPER_LEADERBOARD,
	SNAKE_MENU,
	SNAKE_PLAY,
	SNAKE_LEADERBOARD
}
