package com.germistry.gui;

public enum PanelName {

	MAIN_MENU,
	TWENTY28_MENU,
	TWENTY28_PLAY,
	TWENTY28_LEADERBOARD,
	KRACKOUT_MENU,
	KRACKOUT_PLAY,
	KRACKOUT_LEADERBOARD,
	MINESWEEPER_MENU,
	MINESWEEPER_PLAY,
	MINESWEEPER_LEADERBOARD,
	INVADERS_MENU,
	INVADERS_PLAY,
	INVADERS_LEADERBOARD,
	PIPES_MENU,
	PIPES_PLAY,
	PIPES_LEADERBOARD,
	RIVERRAID_MENU,
	RIVERRAID_PLAY,
	RIVERRAID_LEADERBOARD,
	SNAKE_MENU,
	SNAKE_PLAY,
	SNAKE_LEADERBOARD,
	SUDOKU_MENU,
	SUDOKU_PLAY,
	SUDOKU_LEADERBOARD,
	TETRIS_MENU,
	TETRIS_PLAY,
	TETRIS_LEADERBOARD
	
}
